service: gcf-serverless-tutorial # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs
  project: wh-tutorials
  credentials: secrets/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gcloudignore
    - .gitignore
    - .git/**

functions:
  getUsers:
    handler: getUsers
    events:
      - http: path
  getUser:
    handler: getUser
    events:
      - http: path
